# Generated by Django 2.0.4 on 2018-07-31 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('interview_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('dates', models.TextField(blank=True, default='', max_length=2000)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('first', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='first', to='jobs.Position')),
                ('second', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second', to='jobs.Position')),
                ('third', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third', to='jobs.Position')),
            ],
        ),
    ]
