# Generated by Django 2.0.4 on 2018-07-28 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='gangleader',
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
