# Generated by Django 2.0.2 on 2018-07-30 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20180728_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dates',
            old_name='user',
            new_name='applicant',
        ),
    ]
