# Generated by Django 2.0.2 on 2018-10-21 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20181004_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('show_countdown', models.BooleanField(default=False)),
            ],
        ),
    ]
