# Generated by Django 2.0.4 on 2018-07-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_calendar_gangleader_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='dates',
            field=models.TextField(default=None, max_length=2000, null=True),
        ),
    ]
