# Generated by Django 2.0.4 on 2018-07-27 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0005_auto_20180724_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='name_of_interviewer',
        ),
        migrations.AddField(
            model_name='position',
            name='interviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='gangleader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dates',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gang',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gangs', to='jobs.Section'),
        ),
        migrations.AlterField(
            model_name='position',
            name='gang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='jobs.Gang'),
        ),
        migrations.AlterField(
            model_name='project',
            name='gang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='jobs.Gang'),
        ),
    ]
