# Generated by Django 2.0.4 on 2018-07-27 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20180727_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='application',
            name='ranking',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='gangleader',
        ),
        migrations.RemoveField(
            model_name='dates',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='first',
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='second',
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='third',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
        migrations.DeleteModel(
            name='Dates',
        ),
        migrations.DeleteModel(
            name='Ranking',
        ),
    ]
