# Generated by Django 2.0.4 on 2018-07-28 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20180727_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='interviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
