# Generated by Django 2.0.4 on 2018-10-04 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20181004_0926'),
        ('accounts', '0002_auto_20180930_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewer',
            name='gang',
        ),
        migrations.RemoveField(
            model_name='interviewer',
            name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_interviewer',
            new_name='interviewer',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_recruiter',
            new_name='recruiter',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_superuser',
            new_name='superuser',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_applicant',
        ),
        migrations.AddField(
            model_name='user',
            name='gang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='jobs.Gang'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('NE', 'Not evaluated'), ('IS', 'Interview set'), ('IC', 'Interview confirmed'), ('ID', 'Interviewed'), ('NM', 'Not met'), ('AC', 'Accepted'), ('PP', 'Possibly participant')], default='NE', max_length=2),
        ),
        migrations.DeleteModel(
            name='Interviewer',
        ),
    ]
