# Generated by Django 2.0.2 on 2018-04-12 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('phone_number', models.CharField(max_length=12)),
                ('trondheim', models.BooleanField(default=False)),
                ('student', models.BooleanField(default=False)),
                ('interview_time', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=20000)),
                ('email', models.EmailField(max_length=200)),
                ('name_of_interviewer', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=12)),
                ('gang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Gang')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Gang')),
                ('leader', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('information', models.TextField(max_length=20000)),
                ('leader', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gang',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Section'),
        ),
        migrations.AddField(
            model_name='application',
            name='positions',
            field=models.ManyToManyField(to='job.Position'),
        ),
    ]
