# Generated by Django 2.0.4 on 2018-07-22 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first', to='job.Position')),
                ('second', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second', to='job.Position')),
                ('third', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third', to='job.Position')),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='positions',
        ),
        migrations.RemoveField(
            model_name='application',
            name='student',
        ),
        migrations.RemoveField(
            model_name='application',
            name='trondheim',
        ),
        migrations.AlterField(
            model_name='application',
            name='interview_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ranking',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.Ranking'),
        ),
    ]
