# Generated by Django 2.0.2 on 2018-02-22 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applicant_name',
            new_name='applicant',
        ),
    ]
