# Generated by Django 2.0.4 on 2018-07-23 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='gangleader_dates',
        ),
    ]
