# Generated by Django 2.0.4 on 2018-07-22 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='times',
            new_name='dates',
        ),
    ]
