# Generated by Django 2.0.2 on 2018-04-26 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20180426_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='interview_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='second',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='second', to='job.Position'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='third',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='third', to='job.Position'),
        ),
    ]
