# Generated by Django 2.0.2 on 2018-03-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20180309_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='position',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
