# Generated by Django 2.0.2 on 2018-04-26 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20180426_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ranking',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.Ranking'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='second',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second', to='job.Position'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='third',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third', to='job.Position'),
        ),
    ]
