# Generated by Django 2.0.2 on 2018-02-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20180222_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='phone_number',
            field=models.IntegerField(default=12346578),
            preserve_default=False,
        ),
    ]
