# Generated by Django 2.0.2 on 2018-03-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20180312_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='interview_time',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
