# Generated by Django 2.0.4 on 2018-07-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20180724_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='dates',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True),
        ),
    ]
