# Generated by Django 2.0.2 on 2018-03-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_application_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='trondheim',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='application',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
