# Generated by Django 2.0.4 on 2018-07-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20180724_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='dates',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
