# Generated by Django 2.0.2 on 2018-03-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20180313_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='interview_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
