# Generated by Django 2.0.2 on 2018-03-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20180302_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='job',
        ),
        migrations.AddField(
            model_name='application',
            name='jobs',
            field=models.ManyToManyField(to='job.Job'),
        ),
    ]
