# Generated by Django 2.0.2 on 2018-03-04 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20180302_1742'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Position',
        ),
    ]
