# Generated by Django 2.0.2 on 2018-03-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20180304_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='jobs',
            new_name='positions',
        ),
        migrations.RemoveField(
            model_name='gang',
            name='leader',
        ),
    ]
