# Generated by Django 2.0.2 on 2018-03-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_auto_20180304_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='information',
            field=models.TextField(default=0, max_length=20000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.TextField(max_length=20000),
        ),
    ]
