# Generated by Django 2.0.2 on 2018-03-06 21:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_auto_20180306_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='text',
            field=models.TextField(max_length=2000),
        ),
    ]
