# Generated by Django 2.0.2 on 2018-03-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_auto_20180306_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='email',
            field=models.EmailField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
