# Generated by Django 2.0.2 on 2018-03-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_position_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='name_of_interviewer',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='phone_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
