# Generated by Django 2.0.2 on 2018-03-06 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_auto_20180306_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='phone_number',
        ),
    ]
