# Generated by Django 2.0.2 on 2018-03-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_remove_position_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='phone_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
